ALTER TABLE telemetry_records ADD COLUMN IF NOT EXISTS location_valid BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE schedule_stops ADD COLUMN IF NOT EXISTS manual_fill BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE predictions_log ADD COLUMN IF NOT EXISTS model_version VARCHAR(128);
